name: Code Guide by @mdo
description: Standards for developing consistent, flexible, and sustainable HTML and CSS.
url: https://codeguide.co
permalink: pretty
sass:
  style: compressed
version: 4.0.0
og_image: https://github.com/mdo/code-guide/blob/gh-pages/code-guide-social.png
